### ISSUE TITLE
Issues with the provided instructions

### ISSUE THREAD

**Issue by Bourne227** [thecharm/BDoG#2]
Hi there,

I have been using the BDoG and followed the manual provided to reproduce the results. However, the outputs I obtain do not match the expected results(there is a mismatch between Instructblip.py's input and output ), there might be an issue with the current Instructblip.py file. [image](https://github.com/user-attachments/assets/d6e8bdd0-0581-4d95-ae74-c204209651a7)

I would greatly appreciate your guidance on resolving these issues. Thank you for your time and assistance!

**Comment by YongLD** [comment]
This issue is caused by the input sequence being too long. You can set `max_length=100` to a larger value to suit the scenarios you need.
```pytohn
# vlmeval/vlm/instructblip.py line22
def generate(self, prompt, image_path, dataset=None, max_length=512):
```

**Comment by Bourne227** [comment]
Thanks for replying! I have tried that, and it seems like the maximum length supported by InstructBlip is 512. The example dataset 'ScienceQA_TEST' encountered many length issues. I tried truncating the input, but this greatly affects the results. May you help me check that?

**Comment by YongLD** [comment]
You can handle longer sequence inputs in two ways: (1) Emphasize the sequence output length in the prompt; (2) Use graph sparsification or graph clustering methods to optimize the output graph structure in a simple manner as shown below. Since other models do not have such strict sequence input constraints, this type of method was not used in the paper: 
```python
# Graph sparsification
def sparsify_graph(graph, threshold):
    sparse_graph = graph.copy()
    for edge, weight in weights.items():
        if weight < threshold:
            sparse_graph.remove_edge(*edge)
    return sparse_graph
```
```python
# Graph structure clustering
def spectral_clustering(graph, n_clusters):
    # Calculate Laplacian matrix
    laplacian = nx.laplacian_matrix(graph)
    # Eigenvalue decomposition
    eigenvalues, eigenvectors = np.linalg.eigh(laplacian.toarray())
    # K-means clustering
    kmeans = KMeans(n_clusters=n_clusters)
    clusters = kmeans.fit_predict(eigenvectors[:, :n_clusters])
    return clusters
```
However, I still recommend trying other models that do not have sequence length limitations, as LLMs possess stronger information integration capabilities.

**Comment by Bourne227** [comment]
Thank you so much! I used the model weights suggested in the manual (https://huggingface.co/Salesforce/instructblip-vicuna-13b) which cause this problem. I will try your methods also switch to other models. Your response means a lot!🫶
